version: "3.8"


services:

  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: my_secret_pw_shh
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "9906:3306"
    networks:
      - app-network

  web:
    environment:
      APP_URL: http://127.0.0.1:${HTTP_PORT}
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: test_db
      DB_USERNAME: root
      DB_PASSWORD: my_secret_pw_shh
      SERVICE_TAGS: dev
      SERVICE_NAME: web
      PATH_LOCAL: ${PATH_LOCAL:-.}
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ${PATH_LOCAL}:/var/www/html/
    image: ${LARAVEL_IMAGE}
    container_name: php_web
    depends_on:
      - db
    stdin_open: true
    tty: true
    working_dir: /var/www/html/
    networks:
      - app-network


networks:
  app-network:
    driver: bridge